require:
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "*.gemspec"
    - "./vendor/bundle/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/MethodParameterName:
  Enabled: false
