name: Ruby non-MRI Versions

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    env:
      BUNDLE_GEMFILE: Gemfile.alt-legacy
      NO_COVERAGE: true
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "jruby-head"
          - "jruby-9.4"
          - "truffleruby-24.1.1"
          - "truffleruby-head"
          - "truffleruby+graalvm-head"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_ONLY: default
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the tests
        run: bundle exec rake -f Rakefile.alt-legacy
          
